-- GcTest.lua (GAMECUBE ONLY)
--
-- Switches for testing a build in Dolphin without touching the pad (keys sent to Dolphin can land
-- in whatever window has the focus). The PC's S2_* environment variables cannot reach a console,
-- so these stand in for them. ALL OFF in anything shipped: GcTest = {}.
--
--     pick = n          on the stage select, choose stage n by itself (0: 1 to 7, then round again)
--     exit = seconds    leave a stage that long after it starts, as EXIT from the pause menu does
--     free = true       free memory, in KB, in the corner of every screen
--     wait = seconds    how long the stage select shows before `pick` chooses (default 3)
--     marathon = true   on the title menu, choose MARATHON by itself (after `wait`)
--     thenMarathon = true   after `pick`'s one stage, back on the stage select, a MARATHON
--     timeAttack = true     with `marathon`: a TIME ATTACK instead
--     start = n             the run's starting difficulty (1-7); lives = n: a time attack's lives
--     rounds = n            the run's zones (0 endless)
--     census = seconds      every asset's memory and the heap in the log that often (a log build)
--     hold = seconds    in a marathon, change its colours that often, as a zone's hold does
--     holdTo = n        ...always to palette n (else the next one round)
--     autoplay = true   the stage plays itself (the PC's S2_AUTOPLAY)
--     spin = seconds    a spin dash that long into a stage, and every 8 s after (S2_TEST_SPIN)
--     readout = true    fps, the worst frame, pieces drawn and free memory, on screen in a stage
--     perf = true       the stage's parts timed one by one into the SD perf log's LUA lines
--                       (Screens.lua TimeStageParts; needs a log build)

GcTest = {}
